export default // 20210518090354
// https://api.github.com/users/ziaukhan

{
  login: "ziaukhan",
  id: 545458,
  node_id: "MDQ6VXNlcjU0NTQ1OA==",
  avatar_url: "https://avatars.githubusercontent.com/u/545458?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ziaukhan",
  html_url: "https://github.com/ziaukhan",
  followers_url: "https://api.github.com/users/ziaukhan/followers",
  following_url: "https://api.github.com/users/ziaukhan/following{/other_user}",
  gists_url: "https://api.github.com/users/ziaukhan/gists{/gist_id}",
  starred_url: "https://api.github.com/users/ziaukhan/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ziaukhan/subscriptions",
  organizations_url: "https://api.github.com/users/ziaukhan/orgs",
  repos_url: "https://api.github.com/users/ziaukhan/repos",
  events_url: "https://api.github.com/users/ziaukhan/events{/privacy}",
  received_events_url: "https://api.github.com/users/ziaukhan/received_events",
  type: "User",
  site_admin: false,
  name: "Zia Khan",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 16,
  public_gists: 0,
  followers: 1268,
  following: 0,
  created_at: "2011-01-03T14:24:08Z",
  updated_at: "2021-05-12T16:30:32Z",
};
