export default // 20210518090509
// https://api.github.com/users/ziaukhan/followers

[
  {
    login: "hrizvi",
    id: 1534450,
    node_id: "MDQ6VXNlcjE1MzQ0NTA=",
    avatar_url: "https://avatars.githubusercontent.com/u/1534450?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hrizvi",
    html_url: "https://github.com/hrizvi",
    followers_url: "https://api.github.com/users/hrizvi/followers",
    following_url: "https://api.github.com/users/hrizvi/following{/other_user}",
    gists_url: "https://api.github.com/users/hrizvi/gists{/gist_id}",
    starred_url: "https://api.github.com/users/hrizvi/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hrizvi/subscriptions",
    organizations_url: "https://api.github.com/users/hrizvi/orgs",
    repos_url: "https://api.github.com/users/hrizvi/repos",
    events_url: "https://api.github.com/users/hrizvi/events{/privacy}",
    received_events_url: "https://api.github.com/users/hrizvi/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Sharique-Hasan",
    id: 2499521,
    node_id: "MDQ6VXNlcjI0OTk1MjE=",
    avatar_url: "https://avatars.githubusercontent.com/u/2499521?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Sharique-Hasan",
    html_url: "https://github.com/Sharique-Hasan",
    followers_url: "https://api.github.com/users/Sharique-Hasan/followers",
    following_url:
      "https://api.github.com/users/Sharique-Hasan/following{/other_user}",
    gists_url: "https://api.github.com/users/Sharique-Hasan/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Sharique-Hasan/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Sharique-Hasan/subscriptions",
    organizations_url: "https://api.github.com/users/Sharique-Hasan/orgs",
    repos_url: "https://api.github.com/users/Sharique-Hasan/repos",
    events_url: "https://api.github.com/users/Sharique-Hasan/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Sharique-Hasan/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "hammadtariq",
    id: 4215644,
    node_id: "MDQ6VXNlcjQyMTU2NDQ=",
    avatar_url: "https://avatars.githubusercontent.com/u/4215644?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hammadtariq",
    html_url: "https://github.com/hammadtariq",
    followers_url: "https://api.github.com/users/hammadtariq/followers",
    following_url:
      "https://api.github.com/users/hammadtariq/following{/other_user}",
    gists_url: "https://api.github.com/users/hammadtariq/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/hammadtariq/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hammadtariq/subscriptions",
    organizations_url: "https://api.github.com/users/hammadtariq/orgs",
    repos_url: "https://api.github.com/users/hammadtariq/repos",
    events_url: "https://api.github.com/users/hammadtariq/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/hammadtariq/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "badrmerchant",
    id: 1376008,
    node_id: "MDQ6VXNlcjEzNzYwMDg=",
    avatar_url: "https://avatars.githubusercontent.com/u/1376008?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/badrmerchant",
    html_url: "https://github.com/badrmerchant",
    followers_url: "https://api.github.com/users/badrmerchant/followers",
    following_url:
      "https://api.github.com/users/badrmerchant/following{/other_user}",
    gists_url: "https://api.github.com/users/badrmerchant/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/badrmerchant/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/badrmerchant/subscriptions",
    organizations_url: "https://api.github.com/users/badrmerchant/orgs",
    repos_url: "https://api.github.com/users/badrmerchant/repos",
    events_url: "https://api.github.com/users/badrmerchant/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/badrmerchant/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "laeeqrind",
    id: 4216736,
    node_id: "MDQ6VXNlcjQyMTY3MzY=",
    avatar_url: "https://avatars.githubusercontent.com/u/4216736?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/laeeqrind",
    html_url: "https://github.com/laeeqrind",
    followers_url: "https://api.github.com/users/laeeqrind/followers",
    following_url:
      "https://api.github.com/users/laeeqrind/following{/other_user}",
    gists_url: "https://api.github.com/users/laeeqrind/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/laeeqrind/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/laeeqrind/subscriptions",
    organizations_url: "https://api.github.com/users/laeeqrind/orgs",
    repos_url: "https://api.github.com/users/laeeqrind/repos",
    events_url: "https://api.github.com/users/laeeqrind/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/laeeqrind/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "khanani92",
    id: 3908909,
    node_id: "MDQ6VXNlcjM5MDg5MDk=",
    avatar_url: "https://avatars.githubusercontent.com/u/3908909?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/khanani92",
    html_url: "https://github.com/khanani92",
    followers_url: "https://api.github.com/users/khanani92/followers",
    following_url:
      "https://api.github.com/users/khanani92/following{/other_user}",
    gists_url: "https://api.github.com/users/khanani92/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/khanani92/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/khanani92/subscriptions",
    organizations_url: "https://api.github.com/users/khanani92/orgs",
    repos_url: "https://api.github.com/users/khanani92/repos",
    events_url: "https://api.github.com/users/khanani92/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/khanani92/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "srehanuddin",
    id: 1668868,
    node_id: "MDQ6VXNlcjE2Njg4Njg=",
    avatar_url: "https://avatars.githubusercontent.com/u/1668868?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/srehanuddin",
    html_url: "https://github.com/srehanuddin",
    followers_url: "https://api.github.com/users/srehanuddin/followers",
    following_url:
      "https://api.github.com/users/srehanuddin/following{/other_user}",
    gists_url: "https://api.github.com/users/srehanuddin/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/srehanuddin/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/srehanuddin/subscriptions",
    organizations_url: "https://api.github.com/users/srehanuddin/orgs",
    repos_url: "https://api.github.com/users/srehanuddin/repos",
    events_url: "https://api.github.com/users/srehanuddin/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/srehanuddin/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "MohammedTaha",
    id: 3276864,
    node_id: "MDQ6VXNlcjMyNzY4NjQ=",
    avatar_url: "https://avatars.githubusercontent.com/u/3276864?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/MohammedTaha",
    html_url: "https://github.com/MohammedTaha",
    followers_url: "https://api.github.com/users/MohammedTaha/followers",
    following_url:
      "https://api.github.com/users/MohammedTaha/following{/other_user}",
    gists_url: "https://api.github.com/users/MohammedTaha/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/MohammedTaha/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/MohammedTaha/subscriptions",
    organizations_url: "https://api.github.com/users/MohammedTaha/orgs",
    repos_url: "https://api.github.com/users/MohammedTaha/repos",
    events_url: "https://api.github.com/users/MohammedTaha/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/MohammedTaha/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "hussainmuzzamil",
    id: 1318199,
    node_id: "MDQ6VXNlcjEzMTgxOTk=",
    avatar_url: "https://avatars.githubusercontent.com/u/1318199?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hussainmuzzamil",
    html_url: "https://github.com/hussainmuzzamil",
    followers_url: "https://api.github.com/users/hussainmuzzamil/followers",
    following_url:
      "https://api.github.com/users/hussainmuzzamil/following{/other_user}",
    gists_url: "https://api.github.com/users/hussainmuzzamil/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/hussainmuzzamil/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/hussainmuzzamil/subscriptions",
    organizations_url: "https://api.github.com/users/hussainmuzzamil/orgs",
    repos_url: "https://api.github.com/users/hussainmuzzamil/repos",
    events_url: "https://api.github.com/users/hussainmuzzamil/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/hussainmuzzamil/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "0312-2237190",
    id: 5462586,
    node_id: "MDQ6VXNlcjU0NjI1ODY=",
    avatar_url: "https://avatars.githubusercontent.com/u/5462586?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/0312-2237190",
    html_url: "https://github.com/0312-2237190",
    followers_url: "https://api.github.com/users/0312-2237190/followers",
    following_url:
      "https://api.github.com/users/0312-2237190/following{/other_user}",
    gists_url: "https://api.github.com/users/0312-2237190/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/0312-2237190/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/0312-2237190/subscriptions",
    organizations_url: "https://api.github.com/users/0312-2237190/orgs",
    repos_url: "https://api.github.com/users/0312-2237190/repos",
    events_url: "https://api.github.com/users/0312-2237190/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/0312-2237190/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Abdullah440",
    id: 5467895,
    node_id: "MDQ6VXNlcjU0Njc4OTU=",
    avatar_url: "https://avatars.githubusercontent.com/u/5467895?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Abdullah440",
    html_url: "https://github.com/Abdullah440",
    followers_url: "https://api.github.com/users/Abdullah440/followers",
    following_url:
      "https://api.github.com/users/Abdullah440/following{/other_user}",
    gists_url: "https://api.github.com/users/Abdullah440/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Abdullah440/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Abdullah440/subscriptions",
    organizations_url: "https://api.github.com/users/Abdullah440/orgs",
    repos_url: "https://api.github.com/users/Abdullah440/repos",
    events_url: "https://api.github.com/users/Abdullah440/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Abdullah440/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "shery20",
    id: 5562906,
    node_id: "MDQ6VXNlcjU1NjI5MDY=",
    avatar_url: "https://avatars.githubusercontent.com/u/5562906?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/shery20",
    html_url: "https://github.com/shery20",
    followers_url: "https://api.github.com/users/shery20/followers",
    following_url:
      "https://api.github.com/users/shery20/following{/other_user}",
    gists_url: "https://api.github.com/users/shery20/gists{/gist_id}",
    starred_url: "https://api.github.com/users/shery20/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/shery20/subscriptions",
    organizations_url: "https://api.github.com/users/shery20/orgs",
    repos_url: "https://api.github.com/users/shery20/repos",
    events_url: "https://api.github.com/users/shery20/events{/privacy}",
    received_events_url: "https://api.github.com/users/shery20/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "SaadAnees",
    id: 5564617,
    node_id: "MDQ6VXNlcjU1NjQ2MTc=",
    avatar_url: "https://avatars.githubusercontent.com/u/5564617?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/SaadAnees",
    html_url: "https://github.com/SaadAnees",
    followers_url: "https://api.github.com/users/SaadAnees/followers",
    following_url:
      "https://api.github.com/users/SaadAnees/following{/other_user}",
    gists_url: "https://api.github.com/users/SaadAnees/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/SaadAnees/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/SaadAnees/subscriptions",
    organizations_url: "https://api.github.com/users/SaadAnees/orgs",
    repos_url: "https://api.github.com/users/SaadAnees/repos",
    events_url: "https://api.github.com/users/SaadAnees/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/SaadAnees/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "gotoshoaib",
    id: 2571243,
    node_id: "MDQ6VXNlcjI1NzEyNDM=",
    avatar_url: "https://avatars.githubusercontent.com/u/2571243?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/gotoshoaib",
    html_url: "https://github.com/gotoshoaib",
    followers_url: "https://api.github.com/users/gotoshoaib/followers",
    following_url:
      "https://api.github.com/users/gotoshoaib/following{/other_user}",
    gists_url: "https://api.github.com/users/gotoshoaib/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/gotoshoaib/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/gotoshoaib/subscriptions",
    organizations_url: "https://api.github.com/users/gotoshoaib/orgs",
    repos_url: "https://api.github.com/users/gotoshoaib/repos",
    events_url: "https://api.github.com/users/gotoshoaib/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/gotoshoaib/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "MirzaMaaz",
    id: 5557658,
    node_id: "MDQ6VXNlcjU1NTc2NTg=",
    avatar_url: "https://avatars.githubusercontent.com/u/5557658?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/MirzaMaaz",
    html_url: "https://github.com/MirzaMaaz",
    followers_url: "https://api.github.com/users/MirzaMaaz/followers",
    following_url:
      "https://api.github.com/users/MirzaMaaz/following{/other_user}",
    gists_url: "https://api.github.com/users/MirzaMaaz/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/MirzaMaaz/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/MirzaMaaz/subscriptions",
    organizations_url: "https://api.github.com/users/MirzaMaaz/orgs",
    repos_url: "https://api.github.com/users/MirzaMaaz/repos",
    events_url: "https://api.github.com/users/MirzaMaaz/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/MirzaMaaz/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "A1M918",
    id: 5567742,
    node_id: "MDQ6VXNlcjU1Njc3NDI=",
    avatar_url: "https://avatars.githubusercontent.com/u/5567742?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/A1M918",
    html_url: "https://github.com/A1M918",
    followers_url: "https://api.github.com/users/A1M918/followers",
    following_url: "https://api.github.com/users/A1M918/following{/other_user}",
    gists_url: "https://api.github.com/users/A1M918/gists{/gist_id}",
    starred_url: "https://api.github.com/users/A1M918/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/A1M918/subscriptions",
    organizations_url: "https://api.github.com/users/A1M918/orgs",
    repos_url: "https://api.github.com/users/A1M918/repos",
    events_url: "https://api.github.com/users/A1M918/events{/privacy}",
    received_events_url: "https://api.github.com/users/A1M918/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "MuhammadRahil",
    id: 5568679,
    node_id: "MDQ6VXNlcjU1Njg2Nzk=",
    avatar_url: "https://avatars.githubusercontent.com/u/5568679?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/MuhammadRahil",
    html_url: "https://github.com/MuhammadRahil",
    followers_url: "https://api.github.com/users/MuhammadRahil/followers",
    following_url:
      "https://api.github.com/users/MuhammadRahil/following{/other_user}",
    gists_url: "https://api.github.com/users/MuhammadRahil/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/MuhammadRahil/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/MuhammadRahil/subscriptions",
    organizations_url: "https://api.github.com/users/MuhammadRahil/orgs",
    repos_url: "https://api.github.com/users/MuhammadRahil/repos",
    events_url: "https://api.github.com/users/MuhammadRahil/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/MuhammadRahil/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "raza2022",
    id: 5462788,
    node_id: "MDQ6VXNlcjU0NjI3ODg=",
    avatar_url: "https://avatars.githubusercontent.com/u/5462788?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/raza2022",
    html_url: "https://github.com/raza2022",
    followers_url: "https://api.github.com/users/raza2022/followers",
    following_url:
      "https://api.github.com/users/raza2022/following{/other_user}",
    gists_url: "https://api.github.com/users/raza2022/gists{/gist_id}",
    starred_url: "https://api.github.com/users/raza2022/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/raza2022/subscriptions",
    organizations_url: "https://api.github.com/users/raza2022/orgs",
    repos_url: "https://api.github.com/users/raza2022/repos",
    events_url: "https://api.github.com/users/raza2022/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/raza2022/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ravikumark",
    id: 3478485,
    node_id: "MDQ6VXNlcjM0Nzg0ODU=",
    avatar_url: "https://avatars.githubusercontent.com/u/3478485?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ravikumark",
    html_url: "https://github.com/ravikumark",
    followers_url: "https://api.github.com/users/ravikumark/followers",
    following_url:
      "https://api.github.com/users/ravikumark/following{/other_user}",
    gists_url: "https://api.github.com/users/ravikumark/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ravikumark/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ravikumark/subscriptions",
    organizations_url: "https://api.github.com/users/ravikumark/orgs",
    repos_url: "https://api.github.com/users/ravikumark/repos",
    events_url: "https://api.github.com/users/ravikumark/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ravikumark/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Haideralee",
    id: 4715743,
    node_id: "MDQ6VXNlcjQ3MTU3NDM=",
    avatar_url: "https://avatars.githubusercontent.com/u/4715743?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Haideralee",
    html_url: "https://github.com/Haideralee",
    followers_url: "https://api.github.com/users/Haideralee/followers",
    following_url:
      "https://api.github.com/users/Haideralee/following{/other_user}",
    gists_url: "https://api.github.com/users/Haideralee/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Haideralee/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Haideralee/subscriptions",
    organizations_url: "https://api.github.com/users/Haideralee/orgs",
    repos_url: "https://api.github.com/users/Haideralee/repos",
    events_url: "https://api.github.com/users/Haideralee/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Haideralee/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "YaseenGariba",
    id: 5571393,
    node_id: "MDQ6VXNlcjU1NzEzOTM=",
    avatar_url: "https://avatars.githubusercontent.com/u/5571393?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/YaseenGariba",
    html_url: "https://github.com/YaseenGariba",
    followers_url: "https://api.github.com/users/YaseenGariba/followers",
    following_url:
      "https://api.github.com/users/YaseenGariba/following{/other_user}",
    gists_url: "https://api.github.com/users/YaseenGariba/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/YaseenGariba/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/YaseenGariba/subscriptions",
    organizations_url: "https://api.github.com/users/YaseenGariba/orgs",
    repos_url: "https://api.github.com/users/YaseenGariba/repos",
    events_url: "https://api.github.com/users/YaseenGariba/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/YaseenGariba/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "fahadbawani",
    id: 5574692,
    node_id: "MDQ6VXNlcjU1NzQ2OTI=",
    avatar_url: "https://avatars.githubusercontent.com/u/5574692?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/fahadbawani",
    html_url: "https://github.com/fahadbawani",
    followers_url: "https://api.github.com/users/fahadbawani/followers",
    following_url:
      "https://api.github.com/users/fahadbawani/following{/other_user}",
    gists_url: "https://api.github.com/users/fahadbawani/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/fahadbawani/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/fahadbawani/subscriptions",
    organizations_url: "https://api.github.com/users/fahadbawani/orgs",
    repos_url: "https://api.github.com/users/fahadbawani/repos",
    events_url: "https://api.github.com/users/fahadbawani/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/fahadbawani/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "adeelhussain",
    id: 5469508,
    node_id: "MDQ6VXNlcjU0Njk1MDg=",
    avatar_url: "https://avatars.githubusercontent.com/u/5469508?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/adeelhussain",
    html_url: "https://github.com/adeelhussain",
    followers_url: "https://api.github.com/users/adeelhussain/followers",
    following_url:
      "https://api.github.com/users/adeelhussain/following{/other_user}",
    gists_url: "https://api.github.com/users/adeelhussain/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/adeelhussain/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/adeelhussain/subscriptions",
    organizations_url: "https://api.github.com/users/adeelhussain/orgs",
    repos_url: "https://api.github.com/users/adeelhussain/repos",
    events_url: "https://api.github.com/users/adeelhussain/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/adeelhussain/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "yazdanjan",
    id: 5451979,
    node_id: "MDQ6VXNlcjU0NTE5Nzk=",
    avatar_url: "https://avatars.githubusercontent.com/u/5451979?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/yazdanjan",
    html_url: "https://github.com/yazdanjan",
    followers_url: "https://api.github.com/users/yazdanjan/followers",
    following_url:
      "https://api.github.com/users/yazdanjan/following{/other_user}",
    gists_url: "https://api.github.com/users/yazdanjan/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/yazdanjan/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/yazdanjan/subscriptions",
    organizations_url: "https://api.github.com/users/yazdanjan/orgs",
    repos_url: "https://api.github.com/users/yazdanjan/repos",
    events_url: "https://api.github.com/users/yazdanjan/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/yazdanjan/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "azfarshah",
    id: 4232195,
    node_id: "MDQ6VXNlcjQyMzIxOTU=",
    avatar_url: "https://avatars.githubusercontent.com/u/4232195?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/azfarshah",
    html_url: "https://github.com/azfarshah",
    followers_url: "https://api.github.com/users/azfarshah/followers",
    following_url:
      "https://api.github.com/users/azfarshah/following{/other_user}",
    gists_url: "https://api.github.com/users/azfarshah/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/azfarshah/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/azfarshah/subscriptions",
    organizations_url: "https://api.github.com/users/azfarshah/orgs",
    repos_url: "https://api.github.com/users/azfarshah/repos",
    events_url: "https://api.github.com/users/azfarshah/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/azfarshah/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "MFurqanShafiq",
    id: 5567204,
    node_id: "MDQ6VXNlcjU1NjcyMDQ=",
    avatar_url: "https://avatars.githubusercontent.com/u/5567204?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/MFurqanShafiq",
    html_url: "https://github.com/MFurqanShafiq",
    followers_url: "https://api.github.com/users/MFurqanShafiq/followers",
    following_url:
      "https://api.github.com/users/MFurqanShafiq/following{/other_user}",
    gists_url: "https://api.github.com/users/MFurqanShafiq/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/MFurqanShafiq/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/MFurqanShafiq/subscriptions",
    organizations_url: "https://api.github.com/users/MFurqanShafiq/orgs",
    repos_url: "https://api.github.com/users/MFurqanShafiq/repos",
    events_url: "https://api.github.com/users/MFurqanShafiq/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/MFurqanShafiq/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ghazanfarali06",
    id: 5599369,
    node_id: "MDQ6VXNlcjU1OTkzNjk=",
    avatar_url: "https://avatars.githubusercontent.com/u/5599369?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ghazanfarali06",
    html_url: "https://github.com/ghazanfarali06",
    followers_url: "https://api.github.com/users/ghazanfarali06/followers",
    following_url:
      "https://api.github.com/users/ghazanfarali06/following{/other_user}",
    gists_url: "https://api.github.com/users/ghazanfarali06/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ghazanfarali06/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ghazanfarali06/subscriptions",
    organizations_url: "https://api.github.com/users/ghazanfarali06/orgs",
    repos_url: "https://api.github.com/users/ghazanfarali06/repos",
    events_url: "https://api.github.com/users/ghazanfarali06/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ghazanfarali06/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "syedjawadhashmi",
    id: 4591966,
    node_id: "MDQ6VXNlcjQ1OTE5NjY=",
    avatar_url: "https://avatars.githubusercontent.com/u/4591966?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/syedjawadhashmi",
    html_url: "https://github.com/syedjawadhashmi",
    followers_url: "https://api.github.com/users/syedjawadhashmi/followers",
    following_url:
      "https://api.github.com/users/syedjawadhashmi/following{/other_user}",
    gists_url: "https://api.github.com/users/syedjawadhashmi/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/syedjawadhashmi/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/syedjawadhashmi/subscriptions",
    organizations_url: "https://api.github.com/users/syedjawadhashmi/orgs",
    repos_url: "https://api.github.com/users/syedjawadhashmi/repos",
    events_url: "https://api.github.com/users/syedjawadhashmi/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/syedjawadhashmi/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mehmoodulhaq",
    id: 5621024,
    node_id: "MDQ6VXNlcjU2MjEwMjQ=",
    avatar_url: "https://avatars.githubusercontent.com/u/5621024?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mehmoodulhaq",
    html_url: "https://github.com/mehmoodulhaq",
    followers_url: "https://api.github.com/users/mehmoodulhaq/followers",
    following_url:
      "https://api.github.com/users/mehmoodulhaq/following{/other_user}",
    gists_url: "https://api.github.com/users/mehmoodulhaq/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/mehmoodulhaq/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/mehmoodulhaq/subscriptions",
    organizations_url: "https://api.github.com/users/mehmoodulhaq/orgs",
    repos_url: "https://api.github.com/users/mehmoodulhaq/repos",
    events_url: "https://api.github.com/users/mehmoodulhaq/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/mehmoodulhaq/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "shabbar",
    id: 5622277,
    node_id: "MDQ6VXNlcjU2MjIyNzc=",
    avatar_url: "https://avatars.githubusercontent.com/u/5622277?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/shabbar",
    html_url: "https://github.com/shabbar",
    followers_url: "https://api.github.com/users/shabbar/followers",
    following_url:
      "https://api.github.com/users/shabbar/following{/other_user}",
    gists_url: "https://api.github.com/users/shabbar/gists{/gist_id}",
    starred_url: "https://api.github.com/users/shabbar/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/shabbar/subscriptions",
    organizations_url: "https://api.github.com/users/shabbar/orgs",
    repos_url: "https://api.github.com/users/shabbar/repos",
    events_url: "https://api.github.com/users/shabbar/events{/privacy}",
    received_events_url: "https://api.github.com/users/shabbar/received_events",
    type: "User",
    site_admin: false,
  },
];
